from tkinter import *
from tkinter.filedialog import *
from tkinter.messagebox import *


class App():
    def initialize(self):
        self.root = Tk()
        button = Button(self.root,
                                text='root quit',
                                command=self.quit)
        button.pack()
        print(askquestion("gg", "haha"))
        #p2=Label(self.root,text="Mot: ")
        #p2.grid(row=1,column=0)
        #p3=Label(self.root,fg="white",background="black")
        #p3.grid(row=1,column=1)
        #a=Button(self.root,text="A",width=5)
        #a.grid(row=5,column=0)
        #b=Button(self.root,text="B",width=5)
        #b.grid(row=5,column=1)
        #c=Button(self.root,text="C",width=5)
        #c.grid(row=5,column=2)
        #d=Button(self.root,text="D",width=5)
        #d.grid(row=5,column=3)
        #e=Button(self.root,text="E",width=5)
        #e.grid(row=5,column=4)
        #f=Button(self.root,text="F",width=5)
        #f.grid(row=5,column=5)
        #g=Button(self.root,text="G",width=5)
        #g.grid(row=5,column=6)
        #h=Button(self.root,text="H",width=5)
        #h.grid(row=5,column=7)
        #i=Button(self.root,text="I",width=5)
        #i.grid(row=6,column=0)
        #j=Button(self.root,text="J",width=5)
        #j.grid(row=6,column=1)
        #k=Button(self.root,text="K",width=5)
        #k.grid(row=6,column=2)
        #l=Button(self.root,text="L",width=5)
        #l.grid(row=6,column=3)
        #m=Button(self.root,text="M",width=5)
        #m.grid(row=6,column=4)
        #n=Button(self.root,text="N",width=5)
        #n.grid(row=6,column=5)
        #o=Button(self.root,text="O",width=5)
        #o.grid(row=6,column=6)
        #p=Button(self.root,text="P",width=5)
        #p.grid(row=6,column=7)
        #q=Button(self.root,text="Q",width=5)
        #q.grid(row=7,column=0)
        #r=Button(self.root,text="R",width=5)
        #r.grid(row=7,column=1)
        #s=Button(self.root,text="S",width=5)
        #s.grid(row=7,column=2)
        #t=Button(self.root,text="T",width=5)
        #t.grid(row=7,column=3)
        #u=Button(self.root,text="U",width=5)
        #u.grid(row=7,column=4)
        #v=Button(self.root,text="V",width=5)
        #v.grid(row=7,column=5)
        #w=Button(self.root,text="W",width=5)
        #w.grid(row=7,column=6)
        #x=Button(self.root,text="X",width=5)
        #x.grid(row=7, column=7)
        #y=Button(self.root,text="Y",width=5)
        #y.grid(row=8,column=3)
        #z=Button(self.root,text="Z",width=5)
        #z.grid(row=8,column=4)
        self.root.mainloop()

    def ask_file(self):
        filename = askopenfilename(title="Ouvrir votre document",filetypes=[('txt files','.txt'),('all files','.*')])
        fichier = open(filename, "r")
        content = fichier.read()
        fichier.close()


    def quit(self):
        self.root.destroy()